language: go
go: 1.12.x
sudo: true
services:
- docker
install: true
notifications:
  email: false
env:
  - TEST_SUITE=ci-test-build
  - TEST_SUITE=travis-e2e
before_install:
  - go get github.com/mattn/goveralls
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - curl -LO "https://github.com/rancher/k3s/releases/download/v0.3.0/k3s-arm64"
  - sudo mv ./kubectl /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl
  - sudo mv ./k3s-arm64 /usr/local/bin/k3s && sudo chmod +x /usr/local/bin/k3s
  - export GO111MODULE=on
script: 
  - "make $TEST_SUITE"
after_success:
  - test -n "$TRAVIS_TAG" && make build && make push
